### ISSUE TITLE
[Bug Fix] The Auto Tab Discard's "popup" is unreadable when using a dark GTK Theme on Linux - Here how to fix it

### ISSUE THREAD

**Issue by hasB4K** [rNeomy/auto-tab-discard#46]
Hi,

I am using a Dark GTK Theme on Linux with Firefox. And sadly, it is quite difficult to use this plugin since the background color of the popup is almost black with this setup.

After seeing the `data/popup/index.html`, line 9, I would assume you just need to add the following css property:

```css
body
{
    background-color: #FFFFFF !important;
    [...]
}
```

Sadly, I did not directly tested that since it became harder to modify an extension on Firefox (lack of time mostly). However I modified my `userContent.css` in the profile folder of Firefox: `~/.mozilla/firefox/XXXXXXXXXX.default/chrome`, and it works:

```css
@-moz-document url("moz-extension://[...extension-hash...]/data/popup/index.html")
{
    body
    {
        background-color: #FFFFFF !important;
    }
}
```

Thank you for your great add-on!

Best regards,
